# Generated by Django 6.0.4 on 2026-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='declined_requests', to='volunteer.volunteerprofile'),
        ),
    ]
