# Generated by Django 6.0.4 on 2026-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='private_details',
            field=models.TextField(blank=True, help_text='Encrypted: Extra instructions, exact situation.', null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
