# Generated by Django 6.0.4 on 2026-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_helprequest_declined_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
