# Generated by Django 6.0.4 on 2026-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_helprequest_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
