# Generated by Django 6.0.4 on 2026-05-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_helprequest_lattitude_helprequest_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
